### ISSUE TITLE
render.directory.source does not accept expressions

### ISSUE THREAD

**Issue by mgalindor** [archetect/archetect#12]
Would be great if the `render.directory.source accept` expressions like `{{ item }}`

Use Case:
Consider you have a list of optional list of sub modules and you want render only the submodules if the user write it in the prompt. See the next script 

```
---
script:
  - set:
      availableMods:
        value: "data,redis"
        type: array

      modules:
        prompt: "Require any module ({{ availableMods }}) ?"
        type: array
  - for-each:
      in:
        variable: "modules"
      do:
        - if: 
            conditions:
              - is-true: "{{ item in availableMods }}"
            then:
              - display: "Rendering [{{ item }}] module"
              - render:
                  directory:
                    source: "{{ item }}"
            else:
              - display: "Option [{{ item }}] wont be rendered"
```

Now you receive the message  `archetect: Rendering IO Error: No such file or directory (os error 2)`

**Comment by jimmiebfulton** [comment]
TBH, I didn't know anyone was using this outside of my own companies.  I'm working on a new version of Architect (2.X) branch, that uses a full-blown scripting engine (Rhai).  With this engine, you can do anything you want with it, really, including exactly what you are describing.

I'd be interested in hearing how you are using this.  It seems you've figures out a lot considering the lack of documentation.  I currently use it to generate entire service oriented architectures.

**Comment by mgalindor** [comment]
Great to hear about you @jimmiebfulton we started to use this tool as recommendation of Noe Maxihellen my colleague (to not say my boss lol).  The `archetect` tool have been a great discovery to optimize the time to get a new `Service` from scratch specially to forget the scaffolding and boilerplate code (you know configuration classes, properties, dependencies, etc). 

It was a little bit hard at the begging to understand  how does it work or even how much can we do because the documentation is really poor (no offence) I downloaded the code and let me congratulate you because is easy to read even if I'm not a Rust developer I could catch the idea on how the structures are connected (really good job with the structure's names are really descriptive). 

We have many easy templates just to copy sources and replace words but we have one more "flexible" template (which I really proud)  where we are using Hex architecture and you can choose your Adapters EG. have  `GRPC` or `Rest` as **Primary Adapters**(input) in case of **Secondary adapters** (output) we can choose among `JPA`, `MongoDB`, `Redis` or `Rest Client`. 
I got it having a base template folder and a list of secondary folder templates, rendering depending the initial elections. My script may have been smaller but because the limitation (mentioned in the original thread)  I did not find other way than have a big list of if-else xd

```
  - if:
      conditions:
        - is-true: "{{ persistence == 'MongoDB' }}"
      then:
        - set:
            persistence-type:
              value: "mongo"
        - render:
            directory:
              source: layouts_repo_mongo
      else:
        - set:
            persistence-type:
              value: "jpa"
        - render:
            directory:
              source: layouts_repo_jpa
  - if:
      conditions:
        - is-true: "{{ redis == 'repository' or redis == 'cache' }}"
      then:
        - render:
            directory:
              source: layouts_repo_redis
  - render:
      directory:
        source: layouts_base
```

We can not complain, It's such a great tool!! I'm starting to explore Cookiecutter but my first impression is that Archetect is more flexible because the structures in **actions folder**
