### ISSUE TITLE
[Feature Request] Support for Config Directory Pattern

### ISSUE THREAD

**Issue by christiannuss-ybor** [archetect/archetect#22]
In configuration file layering, some services, like `ssh` and `profile` support the following structure
 - `etc/profile.d/something.sh`
 - `etc/ssh.d/some_additional_config`

It'd be nice if Archetect supported the same pattern:
 - `~/.archetect/etc/archetect.yaml`
 - `~/.archetect/etc/archetect.d/some-additional-config.yaml`

YAML would first be loaded from 
 - `~/.archetect/etc/archetect.yaml`

Then find all `*.yaml` in `archetect.d` (if exists), and merge yamls

So:

### `~/.archetect/etc/archetect.yaml`:

```yaml
---
actions:
  default:
    group:
      description: "Default Catalog"
      entries:
        - catalog:
            description: Archetect
            source: https://github.com/archetect/archetect.catalog.git
answers:
  artifactory-host: "my.jfrog.io"
```

### `~/.archetect/etc/archetect.d/custom-answers.yaml`:

```yaml
---
answers:
  org-name: archetect
```

### Effective `archetect.yaml`:

```yaml
### `~/.archetect/etc/archetect.yaml`:

```yaml
---
actions:
  default:
    group:
      description: "Default Catalog"
      entries:
        - catalog:
            description: Archetect
            source: https://github.com/archetect/archetect.catalog.git
answers:
  artifactory-host: "my.jfrog.io"
  org-name: archetect
```
